[pytest]
minversion = 7.0

testpaths =
    tests

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

addopts =
    -ra
    --strict-markers
    --disable-warnings

markers =
    filtering_spatial_median: spatial median filter tests
    filtering_spatial_gaussian: spatial gaussian filter tests
    filtering_spatial_bilateral: spatial bilateral filter tests
    filtering_spatial_gradient: spatial gradient tests
    filtering_spatial_mean_shift: mean shift filter tests
    filtering_spatial_isotropic: isotropic diffusion filter tests
    filtering_spatial_anisotropic: anisotropic diffusion filter tests
    histogram_equalization: histogram equalization tests
    histogram_clahe: adaptive histogram equalization tests
    color_reinhard: Reinhard color correction tests
    



