[pytest]
minversion = 7.0

testpaths =
    tests

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

addopts =
    -ra
    --strict-markers
    --disable-warnings

markers =
    filtering_spatial_median: tests del filtro de mediana espacial
    filtering_spatial_gaussian: tests del filtro gaussiano espacial
    filtering_spatial_bilateral: tests del filtro bilateral espacial
    filtering_spatial_gradient: tests de gradientes espaciales
    filtering_spatial_mean_shift: tests del filtro mean shift
    filtering_spatial_isotropic: tests del filtro de difusión isotrópica
    filtering_spatial_anisotropic: tests del filtro de difusión anisotrópica



